#!MC 1410
$!READDATASET  '"-F" "1" /home/ws/ht72/programming/git/tecplot-tools/examples/test.hdf "-D" "6" "X" "Y" "Z" "x_velocity" "y_velocity" "z_velocity"  "-K" "1" "1" "1"'
  DATASETREADER = 'HDF5 Loader'
  READDATAOPTION = NEW
  RESETSTYLE = YES
  ASSIGNSTRANDIDS = NO
  INITIALPLOTTYPE = CARTESIAN3D
  INITIALPLOTFIRSTZONEONLY = NO
  ADDZONESTOEXISTINGSTRANDS = NO
  VARLOADMODE = BYNAME
$!THREEDAXIS XDETAIL{VARNUM = 1}
$!THREEDAXIS YDETAIL{VARNUM = 2}
$!THREEDAXIS ZDETAIL{VARNUM = 3}
